AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World with SAM
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs12.x
    Timeout: 5
Resources:
  eventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Handler: logger.handler
      Timeout: 3
      Events:
        GetLogs:
          Type: Api
          Properties:
            Method: get
            Path: /logs
        FileUpload:
          Type: S3
          Properties:
            Bucket:
              Ref: MyBucket
            Events: s3:ObjectCreated:*
      CodeUri: s3://tracy-sam/9c7d8d5c39396d259ffe4185a138ac0b
  MyBucket:
    Type: AWS::S3::Bucket
  addNumbers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add.handler
      Events:
        PostAdd:
          Type: Api
          Properties:
            Method: post
            Path: /add
      CodeUri: s3://tracy-sam/9c7d8d5c39396d259ffe4185a138ac0b
