service: hello-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: 'ap-northeast-1'
  stage: dev
  memorySize: 256 # global varable
  timeout: 5

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 3
    vpc:
      securityGroupIds:
        - sg-60a11a29
      subnetIds:
        - subnet-548c5c1c
        - subnet-99875cb2
        - subnet-d5b9ba8e
  
  add:
    handler: add.add
    events:
      - http:
          path: math/add
          method: post
          cors: true
