service: hello-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: 'ap-northeast-1'
  stage: dev
  memorySize: 256 # global varable
  timeout: 5

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 3
  
  add:
    handler: add.add
    events:
      - http:
          path: math/add
          method: post
          cors: true
